#!/bin/bash
# Create a GitHub issue for technology best practices updates
# Usage: ./create-tech-update-issue.sh <outdated_json>

set -euo pipefail

# Get outdated JSON from argument or stdin
outdated_json="${1:-$(cat)}"

# Parse JSON and build the findings
entries=$(echo "$outdated_json" | jq -r 'to_entries[] | "\(.key)|\(.value.current)|\(.value.latest)|\(.value.wanted)"')

# Build the body with dependency information
findings="### Outdated Dependencies"$'\n'$'\n'
while IFS='|' read -r pkg current latest wanted; do
  findings+="- **${pkg}**: ${current} → ${latest}"$'\n'
  findings+="    - Current: ${current}"$'\n'
  findings+="    - Latest: ${latest}"$'\n'
  findings+="    - Wanted: ${wanted}"$'\n'
done <<< "$entries"

# Create the full issue body
body="## Technology Best Practices Update

Several dependencies have newer versions available. This may indicate:
- Security updates
- New features that improve best practices
- Breaking changes requiring code updates

$findings

### Recommended Actions

1. Review each package's changelog for breaking changes
2. Test compatibility in development
3. Update package versions carefully
4. Verify all tests pass after updates

---
⚠️ **Note**: Technology evolves. When major versions bump, best practices often change. Review release notes to see if documentation or approaches need updating.

Generated by Technology Best Practices Monitor"

# Create the issue using GitHub CLI
gh issue create \
  --title "chore: technology best practices update available" \
  --body "$body" \
  --assignee dsdeboer \
  --label maintenance \
  --label dependencies \
  --label best-practices
